[tool.git_changelog]
provider = "github"
repository = "WDGPH/viper-pipeline"   # update to your actual repo slug
convention = "angular"                # compatible with Conventional Commits
output = "CHANGELOG.md"
sections = [
  { title = "Added",    tags = ["feat", "add"] },
  { title = "Changed",  tags = ["refactor", "change", "update"] },
  { title = "Fixed",    tags = ["fix", "bug"] },
  { title = "Docs",     tags = ["docs"] },
  { title = "Other",    tags = [] }
]
