# Configuration for QR code payloads.
#
# Strings support Python-style placeholders. Allowed placeholders:
# client_id, first_name, last_name, name, date_of_birth, date_of_birth_iso,
# school, city, postal_code, province, street_address, language, language_code,
# delivery_date.
#
# Uncomment delivery_date to override the default value used for age checks.
# delivery_date: "2025-04-08"

qr_payload_template:
  english: "https://www.test-immunization.ca/update?client_id={client_id}&dob={date_of_birth_iso}&lang={language_code}"
  french: "https://www.test-immunization.ca/update?client_id={client_id}&dob={date_of_birth_iso}&lang={language_code}"

allowed_placeholders:
  - client_id
  - first_name
  - last_name
  - name
  - date_of_birth
  - date_of_birth_iso
  - school
  - city
  - postal_code
  - province
  - street_address
  - language
  - language_code
  - delivery_date
